FROM ubuntu:14.04

RUN apt-get update

# Create  build user 
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/build && \
    echo "build:x:${uid}:${gid}:Abc,,,:/home/build:/bin/bash" >> /etc/passwd && \
    echo "build:x:${uid}:" >> /etc/group && \
    echo "build ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/build && \
    chmod 0440 /etc/sudoers.d/build && \
    chown ${uid}:${gid} -R /home/build

# Install required libs
RUN apt-get update && \
    dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y lib32bz2-1.0 libuuid1:i386

# Copy the current directory contents into the container at /data
ADD slave /data

# Make port 443 available to the world outside this container
EXPOSE 443

USER build
ENV HOME /home/build
WORKDIR $HOME
CMD /bin/bash
